[Feat]: Reset Password
Jessaleem/airbnb_backend pull request #27
Opened 2022-09-06 00:56 UTC by Jessaleem

### Descripción
[//]: <> (Aca debe ir la descripcion del PullRequest, que es? que hace?)
Add changePassword controller with validations.
1. Search user by id.
2. Compares current password entered in client with database password.
3. Compares current password with new password entered in client, must be different.
4. Encrypt and update new password.

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ X] 👌 Terminado y listo

### Cómo probar?
[//]: <> (Pasos necesarios para probar esta funcionalidad)
Make validations with different cases in postman or in client when you download the feat/adjustUpdateUserData branch

### Screenshots (si es aplicable)
[//]: <> (Capturas de pantalla que ayuden a entender que hiciste en este PR)
<img width="923" alt="image" src="https://user-images.githubusercontent.com/105444324/188525280-1fa02e72-d747-467b-a5c1-8322501e2ded.png">

### Scope

- [X] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)

2022-09-06 01:28 UTC, khriztianmoreno requested changes

2022-09-06 01:28 UTC, khriztianmoreno commented on auth/local/auth.controller.js
> +    const { id } = req.params;
What do you think if we obtain this data but directly from the user's token, through the `req.user`?

2022-09-06 01:28 UTC, khriztianmoreno commented on auth/local/index.js
> +router.patch('/:id', isAuthenticated, changePassword);
It would make more sense if the path was:

```suggestion
router.patch('/change-password', isAuthenticated, changePassword);
```

2022-09-06 01:28 UTC, khriztianmoreno commented on auth/local/auth.controller.js
> +    const { id } = req.params;
```js
const { id } = req.user
```

2022-09-07 15:56 UTC, Dhruva108 approved these changes
Vamo' pa'lante!

2022-09-07 16:04 UTC, khriztianmoreno approved these changes

2022-09-07 16:06 UTC, merged